version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.15
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CICLE_BRANCH}
      - run:
          name: Show current directory
          command: pwd
      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Linting TypeScript files
          command: npm run lint:check
      - run:
          name: Linting sass files
          command: npm run stylelint:check
      - run:
          name: Checking code formatting
          command: npm run format:check
      - run:
          name: Building
          command: npm run build
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - dist
            - package.json
            - firebase.json
            - .firebaserc
  deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:10.15
    steps:
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
      - restore_cache:
          keys:
            - v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Deploy Master to Firebase
          command: npm run deploy -- --token=$FIREBASE_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
